### ISSUE TITLE
Current version in Appstore don’t work on iOS 6

### ISSUE THREAD

**Issue by berlincount** [Navideck/Romo-X#2]
Hi!

iPod touch MC540FD/A running iOS 6.1.6 (10B500), which is the latest ...

.. Romo X App 1.4.5 updated 29.3.2020 requires iOS 8.0 or later :(

What do I do?

  count

**Comment by fotiDim** [comment]
Hi, are we talking about the code of this repo or the Romo X app on the App Store? Either case you should be able to download the latest compatible version with iOS 6. Please elaborate so that I can assist better.

**Comment by berlincount** [comment]
I haven’t tried compiling myself, but the Romo X App in the (German) App Store can’t be installed - it gives the OS version error before even prompting to pay for a purchase.

**Comment by fotiDim** [comment]
Doesn't it give you something similar to this dialog?
![image](https://user-images.githubusercontent.com/2326415/78589698-e6953680-7840-11ea-9f6b-74fbccf0fd47.png)

**Comment by fotiDim** [comment]
Hmmm, I see. You need to have it already purchased to get this dialog. What you can do is to use another device to purchase it and then you should be also able to download it on your iPod touch. See more [here](https://appletoolbox.com/download-incompatible-apps-on-an-older-iphone-ipad-or-ipod-touch/#2_Use_an_older_version_of_iTunes_to_download_the_app).

**Comment by berlincount** [comment]
![DE7364BD-127C-4C2A-9E87-7156D5D64569](https://user-images.githubusercontent.com/545500/78590340-fbbe9500-7841-11ea-8164-9e3eefdc29c1.jpeg)

Ok, I’ll try gifting it to the corresponding account!

**Comment by fotiDim** [comment]
Let me know if it works by gifting. Otherwise just login using that account on a newer device (iOS 8+) just to purchase it and then log out again.

**Comment by berlincount** [comment]
Gifting doesn’t work directly as redeeming doesn’t work on iOS 6, but after Redeeming somewhere else it’s working ... but I don’t seem to have enough power for a video feed. Ah well.

Thanks for the help!!!

**Comment by fotiDim** [comment]
@berlincount glad that it worked! 
By video feed do you mean remote feed using Romo Control X?

**Comment by berlincount** [comment]
Yes

**Comment by fotiDim** [comment]
As stated in the app description an iPhone SE or better is needed for remote video. There might be an improvement in the future regarding this but you are better off using a more recent device.
